PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ma: <http://example.org/music/v1#>

SELECT ?name ?userUrl ?gender
WHERE {
    ?userUrl foaf:name ?name .
    ?userUrl a ma:User .
    OPTIONAL {
        ?userUrl foaf:gender ?gender
    }
}